name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: runner / reviewdog
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-packages-cache-v1-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            npm-packages-cache-v1-${{ hashFiles('./package-lock.json') }}
            npm-packages-cache-v1-
      - name: Install dependencies
        run: npm ci
      - name: Run vue-tsc
        run: npm run type-check | reviewdog -f=tsc -reporter=github-pr-check -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{vue,js,jsx,cjs,mjs,ts,tsx,cts,mts}'
