name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-packages-cache-v1-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            npm-packages-cache-v1-${{ hashFiles('./package-lock.json') }}
            npm-packages-cache-v1-
      - name: Install vue-tsc and typescript
        run: npm install -g vue-tsc@1.0.12 typescript@4.7.4
      - name: Install dependencies
        run: npm ci
      - name: Run vue-tsc
        run: $(npm root -g)/vue-tsc/bin/vue-tsc.js --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-check -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{vue,js,jsx,cjs,mjs,ts,tsx,cts,mts}'
